[project]
name = "invoice-printer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black>=25.9.0",
    "isort>=7.0.0",
    "pyside6>=6.10.0",
    "ruff>=0.14.4",
]
